package io.github.tabforgeai.legacysqlarchitect.tools;

import io.github.tabforgeai.legacysqlarchitect.db.JdbcClient;
import io.github.tabforgeai.legacysqlarchitect.db.MetadataReader;
import io.github.tabforgeai.legacysqlarchitect.model.ColumnInfo;
import io.github.tabforgeai.legacysqlarchitect.model.TableInfo;
import io.modelcontextprotocol.json.McpJsonMapper;
import io.modelcontextprotocol.server.McpSyncServerExchange;
import io.modelcontextprotocol.spec.McpSchema;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.List;
import java.util.Map;
import java.util.function.BiFunction;

/**
 * MCP tool: generate_mermaid_erd
 *
 * Generates a Mermaid Entity-Relationship Diagram (ERD) from live database
 * schema metadata. The output is a plain-text Mermaid diagram that renders
 * natively in GitHub, GitLab, Notion, and any Mermaid-enabled markdown viewer
 * — no diagram editor or image export required.
 *
 * This is the fastest path from "unknown legacy database" to a visual map of
 * its structure. It is particularly useful for onboarding new developers,
 * documenting systems before migration, and understanding FK relationship webs.
 *
 * <p>Tool input parameters:
 * <ul>
 *   <li>{@code schema}          (optional) Database schema name. Defaults to config.json db_schema.</li>
 *   <li>{@code table_filter}    (optional) SQL LIKE pattern to restrict which tables appear
 *                               in the diagram (e.g. {@code "ORD%"} for all order-related tables).
 *                               Defaults to {@code "%"} (all tables).</li>
 *   <li>{@code include_columns} (optional, boolean) If true, column definitions including
 *                               name, type, and PK/FK markers appear inside each entity block.
 *                               If false, entity blocks are empty (useful for very large schemas
 *                               where you just want the relationship map). Defaults to true.</li>
 * </ul>
 *
 * <p>Tool output — example Mermaid ERD text for a simple order schema:
 * <pre>
 * erDiagram
 *     CUSTOMERS {
 *         bigint id PK
 *         varchar name
 *         varchar email
 *     }
 *     ORDERS {
 *         bigint id PK
 *         bigint customer_id FK
 *         varchar status
 *         numeric total
 *     }
 *     ORDER_ITEMS {
 *         bigint id PK
 *         bigint order_id FK
 *         bigint product_id FK
 *         int quantity
 *     }
 *     CUSTOMERS ||--o{ ORDERS : "customer_id"
 *     ORDERS ||--o{ ORDER_ITEMS : "order_id"
 *     PRODUCTS ||--o{ ORDER_ITEMS : "product_id"
 * </pre>
 *
 * <p>To embed the ERD in a GitHub README or Notion page, wrap the output in a
 * fenced code block with the "mermaid" language tag:
 * <pre>
 * ```mermaid
 * erDiagram
 *     ...
 * ```
 * </pre>
 *
 * <p>Downstream usage — this tool's output is consumed by:
 * <ul>
 *   <li>AI agent directly: pastes the diagram into markdown documentation</li>
 *   <li>Human developers: copy-paste into GitHub/GitLab/Notion for immediate visual rendering</li>
 *   <li>{@code generate_documentation} tool: the ERD is embedded as a section in
 *       the full schema documentation generated by that tool</li>
 * </ul>
 *
 * <p>Mermaid ERD relationship notation used by this tool:
 * <pre>
 *   PARENT ||--o{ CHILD : "fk_column"
 *   meaning: one PARENT has zero-or-more CHILD rows (standard FK cardinality)
 * </pre>
 */
public class GenerateMermaidErd implements BiFunction<McpSyncServerExchange, McpSchema.CallToolRequest, McpSchema.CallToolResult> {

    private static final Logger log = LoggerFactory.getLogger(GenerateMermaidErd.class);

    /** Tool name as registered with the MCP server and visible to the AI agent. */
    public static final String TOOL_NAME = "generate_mermaid_erd";

    /** Indentation used inside Mermaid entity blocks. Four spaces per Mermaid convention. */
    private static final String INDENT = "    ";

    private final JdbcClient jdbcClient;

    /**
     * Creates a new GenerateMermaidErd tool instance.
     *
     * @param jdbcClient the shared database client; must be already connected
     */
    public GenerateMermaidErd(JdbcClient jdbcClient) {
        this.jdbcClient = jdbcClient;
    }

    /**
     * Returns the MCP tool definition for generate_mermaid_erd.
     *
     * @param jsonMapper the MCP SDK's JSON mapper for parsing the input schema string
     * @return a fully configured McpSchema.Tool ready for registration
     */
    public static McpSchema.Tool toolDefinition(McpJsonMapper jsonMapper) {
        String inputSchema = """
                {
                  "type": "object",
                  "properties": {
                    "schema": {
                      "type": "string",
                      "description": "Database schema name. Defaults to the schema in config.json."
                    },
                    "table_filter": {
                      "type": "string",
                      "description": "SQL LIKE pattern to restrict tables (e.g. 'ORD%'). Defaults to '%' (all tables)."
                    },
                    "include_columns": {
                      "type": "boolean",
                      "description": "If true (default), column names and types appear inside each entity block. Set to false for large schemas where you only want the relationship map."
                    }
                  }
                }
                """;

        return McpSchema.Tool.builder()
                .name(TOOL_NAME)
                .description("""
                        Generates a Mermaid ERD (Entity-Relationship Diagram) from the live database \
                        schema. The output is plain Mermaid text that renders natively in GitHub, \
                        GitLab, and Notion. Shows tables, columns (with PK/FK markers), and all \
                        foreign-key relationships. Use table_filter to diagram a subset of tables \
                        for large databases.""")
                .inputSchema(jsonMapper, inputSchema)
                .build();
    }

    /**
     * Executes the generate_mermaid_erd tool when called by the AI agent.
     *
     * Reads schema metadata via MetadataReader, then builds the Mermaid ERD text
     * in two passes:
     *   1. Entity blocks: one block per table with optional column definitions
     *   2. Relationship lines: one line per FK column across all tables
     *
     * @param exchange the MCP server exchange context (not used by this tool)
     * @param request  the tool call request with optional schema, table_filter, include_columns
     * @return a CallToolResult containing the Mermaid ERD as plain text
     */
    @Override
    public McpSchema.CallToolResult apply(McpSyncServerExchange exchange, McpSchema.CallToolRequest request) {
        Map<String, Object> args = request.arguments();

        String schema         = resolveSchema(args);
        String tableFilter    = args != null ? (String) args.get("table_filter") : null;
        boolean includeCols   = resolveIncludeColumns(args);

        log.info("Tool '{}' called: schema={}, table_filter={}, include_columns={}",
                TOOL_NAME, schema, tableFilter, includeCols);

        try {
            MetadataReader reader = new MetadataReader(jdbcClient.getConnection());
            List<TableInfo> tables = reader.readTables(schema, tableFilter);

            if (tables.isEmpty()) {
                String msg = tableFilter != null
                        ? "No tables matching '" + tableFilter + "' found in schema '" + schema + "'."
                        : "No tables found in schema '" + schema + "'.";
                return McpSchema.CallToolResult.builder().addTextContent(msg).build();
            }

            String erd = buildMermaidErd(tables, includeCols);

            log.info("generate_mermaid_erd produced ERD for {} tables", tables.size());

            // Wrap in a mermaid code fence so Claude renders it as a code block.
            // Without the fence Claude may HTML-encode spaces and underscores when
            // displaying the result inline, making the copied output unusable.
            return McpSchema.CallToolResult.builder()
                    .addTextContent("```mermaid\n" + erd + "\n```")
                    .build();

        } catch (Exception e) {
            log.error("generate_mermaid_erd failed: {}", e.getMessage(), e);
            return McpSchema.CallToolResult.builder()
                    .addTextContent("Error generating ERD: " + e.getMessage())
                    .isError(true)
                    .build();
        }
    }

    /**
     * Builds the complete Mermaid ERD text from the given list of tables.
     *
     * The diagram is structured in two sections:
     * <ol>
     *   <li>Entity blocks — one per table, with optional column definitions</li>
     *   <li>Relationship lines — one per FK column, in
     *       {@code PARENT ||--o{ CHILD : "fk_column"} notation</li>
     * </ol>
     *
     * Column types are normalized to short names (e.g. "character varying" → "varchar")
     * because Mermaid entity blocks look cleaner with abbreviated type names.
     *
     * @param tables       the list of tables to include in the diagram
     * @param includeCols  if true, column definitions are included in entity blocks
     * @return the complete Mermaid ERD as a multi-line string
     */
    private String buildMermaidErd(List<TableInfo> tables, boolean includeCols) {
        StringBuilder sb = new StringBuilder("erDiagram\n");

        // --- Pass 1: Entity blocks ---
        for (TableInfo table : tables) {
            sb.append(INDENT).append(sanitizeName(table.getName()));

            if (includeCols && !table.getColumns().isEmpty()) {
                sb.append(" {\n");
                for (ColumnInfo col : table.getColumns()) {
                    sb.append(INDENT).append(INDENT)
                      .append(normalizeType(col.getType())).append(" ")
                      .append(col.getName());

                    // Append PK/FK markers — Mermaid supports both, comma-separated
                    boolean hasPk = col.isPrimaryKey();
                    boolean hasFk = col.getForeignKeyTable() != null;
                    if (hasPk && hasFk) {
                        sb.append(" PK,FK");
                    } else if (hasPk) {
                        sb.append(" PK");
                    } else if (hasFk) {
                        sb.append(" FK");
                    }
                    sb.append("\n");
                }
                sb.append(INDENT).append("}\n");
            } else {
                // Empty entity block: Mermaid requires at least the braces
                sb.append(" {\n").append(INDENT).append("}\n");
            }
        }

        // --- Pass 2: Relationship lines ---
        // Collect all FK edges from all tables. Each FK column on a child table
        // produces one relationship line: PARENT ||--o{ CHILD : "fk_column"
        boolean anyRelationships = false;
        for (TableInfo table : tables) {
            for (ColumnInfo col : table.getColumns()) {
                if (col.getForeignKeyTable() != null) {
                    // Only emit the relationship if the referenced (parent) table
                    // is also in our diagram. If it was filtered out by table_filter,
                    // skip the edge to avoid dangling references.
                    String parentName = col.getForeignKeyTable();
                    if (tableInList(tables, parentName)) {
                        if (!anyRelationships) {
                            sb.append("\n"); // blank line separates entities from relationships
                            anyRelationships = true;
                        }
                        // Standard FK cardinality: one parent row, zero-or-more child rows
                        sb.append(INDENT)
                          .append(sanitizeName(parentName))
                          .append(" ||--o{ ")
                          .append(sanitizeName(table.getName()))
                          .append(" : \"")
                          .append(col.getName())
                          .append("\"\n");
                    }
                }
            }
        }

        return sb.toString();
    }

    /**
     * Checks whether a table with the given name exists in the supplied list.
     * Comparison is case-insensitive to handle databases with mixed-case names.
     *
     * @param tables    the list of tables in the current diagram scope
     * @param tableName the table name to search for
     * @return true if the table is present in the list
     */
    private boolean tableInList(List<TableInfo> tables, String tableName) {
        for (TableInfo t : tables) {
            if (t.getName().equalsIgnoreCase(tableName)) {
                return true;
            }
        }
        return false;
    }

    /**
     * Normalizes a SQL type name to a short, Mermaid-friendly abbreviation.
     *
     * Mermaid entity blocks accept any alphanumeric type label, but long
     * PostgreSQL type names like "character varying" clutter the diagram.
     * This method maps common verbose names to their short SQL equivalents.
     *
     * @param type the raw SQL type name from DatabaseMetaData
     * @return a shortened type string suitable for Mermaid entity blocks
     */
    private String normalizeType(String type) {
        if (type == null) return "unknown";
        return switch (type.toLowerCase()) {
            case "character varying", "character varying(n)" -> "varchar";
            case "character"                                  -> "char";
            case "integer"                                    -> "int";
            case "double precision"                           -> "float";
            case "timestamp without time zone"                -> "timestamp";
            case "timestamp with time zone"                   -> "timestamptz";
            case "time without time zone"                     -> "time";
            case "time with time zone"                        -> "timetz";
            default -> type.replace(" ", "_"); // Mermaid doesn't allow spaces in type names
        };
    }

    /**
     * Sanitizes a table or column name for use in a Mermaid diagram.
     *
     * Mermaid entity names must be valid identifiers. Names containing spaces
     * or special characters are quoted with double quotes. Names that are
     * entirely alphanumeric (including underscores) are returned unchanged
     * because quoting is not needed and makes the diagram less readable.
     *
     * @param name the raw database identifier
     * @return a Mermaid-safe identifier string
     */
    private String sanitizeName(String name) {
        if (name == null) return "UNKNOWN";
        // If the name contains only word characters (letters, digits, underscores),
        // return it as-is in uppercase for consistency with Mermaid convention.
        if (name.matches("[\\w]+")) {
            return name.toUpperCase();
        }
        // Otherwise wrap in double quotes to handle spaces and special chars
        return "\"" + name + "\"";
    }

    /**
     * Resolves the schema name from request arguments or config default.
     *
     * @param args the tool call arguments map (may be null)
     * @return the schema name to use
     */
    private String resolveSchema(Map<String, Object> args) {
        if (args != null && args.get("schema") instanceof String s && !s.isBlank()) {
            return s;
        }
        return jdbcClient.getConfig().getDbSchema();
    }

    /**
     * Resolves the include_columns flag from request arguments.
     * Defaults to true if not specified.
     *
     * @param args the tool call arguments map (may be null)
     * @return true if column definitions should be included in entity blocks
     */
    private boolean resolveIncludeColumns(Map<String, Object> args) {
        if (args != null && args.get("include_columns") instanceof Boolean b) {
            return b;
        }
        return true; // default: show columns
    }
}
